server:
  port: 8086
  servlet:
    context-path: /monitor-s
#  ssl:
#    key-store: src/main/resources/www.mihawke.com.jks
#    key-store-password: 2jk97v6869qcp1
#    key-store-type: JKS

spring:
  mvc:

  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://148.70.67.204:3306/monitor2?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    url: jdbc:mysql://localhost:3306/monitor2?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: '123456'
    maxActive: 11
    maxIdle: 6
    minIdle: 3
    initialSize: 30
    testWhileIdle: true
    removeAbandoned: true
    logAbandoned: true
    secondary:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: trues
    params: count=countSql

#坑点0 配置mybatis的xml位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

