package com.ideal.entity;

public class CartEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.serial
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.offer_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer offerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.offer_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String offerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.serial
     *
     * @return the value of cart.serial
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.serial
     *
     * @param serial the value for cart.serial
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setSerial(Integer serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_name
     *
     * @return the value of cart.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_name
     *
     * @param userName the value for cart.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.offer_id
     *
     * @return the value of cart.offer_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.offer_id
     *
     * @param offerId the value for cart.offer_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.offer_name
     *
     * @return the value of cart.offer_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.offer_name
     *
     * @param offerName the value for cart.offer_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName == null ? null : offerName.trim();
    }
}