package com.ideal.entity;

import java.util.Date;

public class UserEstateEntity extends UserEstateEntityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_estate.balance
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Float balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_estate.senior
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer senior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_estate.senior_expiry_date
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Date seniorExpiryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_estate.credits
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer credits;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_estate.balance
     *
     * @return the value of user_estate.balance
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_estate.balance
     *
     * @param balance the value for user_estate.balance
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_estate.senior
     *
     * @return the value of user_estate.senior
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getSenior() {
        return senior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_estate.senior
     *
     * @param senior the value for user_estate.senior
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setSenior(Integer senior) {
        this.senior = senior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_estate.senior_expiry_date
     *
     * @return the value of user_estate.senior_expiry_date
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Date getSeniorExpiryDate() {
        return seniorExpiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_estate.senior_expiry_date
     *
     * @param seniorExpiryDate the value for user_estate.senior_expiry_date
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setSeniorExpiryDate(Date seniorExpiryDate) {
        this.seniorExpiryDate = seniorExpiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_estate.credits
     *
     * @return the value of user_estate.credits
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_estate.credits
     *
     * @param credits the value for user_estate.credits
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }
}