package com.ideal.entity;

public class UserEstateEntityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_estate.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_estate.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_estate.user_id
     *
     * @return the value of user_estate.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_estate.user_id
     *
     * @param userId the value for user_estate.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_estate.user_name
     *
     * @return the value of user_estate.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_estate.user_name
     *
     * @param userName the value for user_estate.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}