package com.ideal.entity;

public class UserAttrEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attr.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attr.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attr.attr_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attr.attr_value
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String attrValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attr.attr_type
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    private String attrType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attr.user_id
     *
     * @return the value of user_attr.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attr.user_id
     *
     * @param userId the value for user_attr.user_id
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attr.user_name
     *
     * @return the value of user_attr.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attr.user_name
     *
     * @param userName the value for user_attr.user_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attr.attr_name
     *
     * @return the value of user_attr.attr_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attr.attr_name
     *
     * @param attrName the value for user_attr.attr_name
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attr.attr_value
     *
     * @return the value of user_attr.attr_value
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attr.attr_value
     *
     * @param attrValue the value for user_attr.attr_value
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attr.attr_type
     *
     * @return the value of user_attr.attr_type
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public String getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attr.attr_type
     *
     * @param attrType the value for user_attr.attr_type
     *
     * @mbg.generated Wed Jan 23 13:22:19 CST 2019
     */
    public void setAttrType(String attrType) {
        this.attrType = attrType == null ? null : attrType.trim();
    }
}